[package]
name = "weather-app"
version = "0.1.0"
authors = ["Michael <mstephenp@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
